"""Synthetic browser check; run against Vite with BMC_URL set if needed."""
import json
import os
from playwright.sync_api import sync_playwright, expect
from customer_helpers import fill_customer

values = dict(insured_id='999999999', insurer='Synthetic', policy_number='123', category='בריאות', subcategory='', product_type='Synthetic coverage', period='', additional_details='Synthetic details', premium='100', frequency='monthly', classification='')
entry = dict(id='1', source_sheet='Synthetic', source_row=2, original=values, values=values, issues=[])
report = dict(instance_id='synthetic', report_date=None, entries=[entry], warnings=[])
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.route('**/api/instance', lambda route: route.fulfill(json={'instance_id': 'synthetic'}))
    page.route('**/api/import', lambda route: route.fulfill(json=report))
    page.goto(os.environ.get('BMC_URL', 'http://127.0.0.1:5174'))
    card = page.locator('.customer-card').filter(has=page.get_by_label('תעודת זהות', exact=True))
    fill_customer(card)
    page.get_by_label('העלאת קובץ Excel הר ביטוח', exact=True).set_input_files({'name': 'synthetic.xlsx', 'mimeType': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'buffer': b'synthetic mocked response'})
    baseline = page.locator('.existing-section')
    proposal = page.locator('.proposed-section')
    expect(baseline.locator('.policy')).to_have_count(1)
    expect(baseline.locator('.totals').get_by_text('פרמיות שנתיות', exact=True)).to_have_count(0)
    expect(page.locator('.proposed-section .policy')).to_have_count(0)
    card.get_by_role('button', name='סיום עריכה').click()
    expect(card.get_by_label('תעודת זהות', exact=True)).not_to_be_visible()
    page.locator('.agent-disclosure > summary').click()
    expect(page.get_by_label('שם פרטי של הסוכן')).to_be_visible()
    page.locator('.agent-disclosure > summary').click()
    expect(proposal).not_to_be_visible()
    expect(baseline.locator('.coverage-details > div')).to_be_visible()
    expect(baseline.locator('td').filter(has=page.locator('.coverage-details'))).to_contain_text('שורה 2')
    expect(baseline.locator('.coverage-details')).to_contain_text('Synthetic details')
    expect(baseline.locator('td > small + .coverage-details')).to_have_count(1)
    baseline.locator('.coverage-details > summary').click()
    expect(baseline.locator('.coverage-details > div')).not_to_be_visible()
    baseline.locator('.coverage-details > summary').click()
    expect(baseline.locator('.coverage-details > div')).to_be_visible()
    expect(baseline.get_by_role('button', name='עריכה', exact=True)).to_have_count(0)
    baseline.get_by_role('button', name='העתקה למצב החדש').click()
    expect(baseline.get_by_role('button', name='הועתק למצב החדש')).to_be_disabled()
    page.get_by_role('tab', name='מצב חדש').click()
    expect(proposal).to_be_visible()
    expect(baseline).not_to_be_visible()
    page.get_by_role('button', name='השוואה', exact=True).click()
    expect(baseline).to_be_visible()
    expect(proposal).to_be_visible()
    proposal.get_by_role('button', name='עריכה', exact=True).click()
    dialog = page.get_by_role('dialog')
    dialog.get_by_label('פרמיה', exact=True).fill('80')
    dialog.get_by_role('button', name='שמירת תיקונים').click()
    expect(baseline.locator('.totals').first).to_contain_text('100.00')
    expect(proposal.locator('.totals').first).to_contain_text('80.00')
    expect(proposal.locator('.totals').get_by_text('פרמיות שנתיות', exact=True)).to_have_count(0)
    proposal.get_by_role('button', name='השוואה למקור', exact=True).click()
    expect(proposal.locator('.delta')).not_to_contain_text('שנתי')
    proposal.get_by_role('button', name='חזרה לפוליסות', exact=True).first.click()
    proposal.get_by_role('button', name='עריכה', exact=True).click()
    dialog.get_by_label('תדירות תשלום', exact=True).select_option('annual')
    dialog.get_by_label('פרמיה', exact=True).fill('120')
    dialog.get_by_role('button', name='שמירת תיקונים').click()
    expect(proposal.locator('.totals').first.get_by_text('פרמיות שנתיות', exact=True)).to_have_count(1)
    expect(proposal.locator('.totals').first).to_contain_text('120.00')
    proposal.get_by_role('button', name='עריכה', exact=True).click()
    dialog.get_by_label('תדירות תשלום', exact=True).select_option('monthly')
    dialog.get_by_label('פרמיה', exact=True).fill('80')
    dialog.get_by_role('button', name='שמירת תיקונים').click()

    proposal.get_by_role('button', name='החרגה', exact=True).click()
    expect(proposal.locator('.totals').first).to_contain_text('0.00')
    expect(baseline.locator('.totals').first).to_contain_text('100.00')
    proposal.get_by_role('button', name='הסרה מהמצב החדש', exact=True).click()
    expect(proposal.locator('.policy')).to_have_count(0)
    expect(baseline.get_by_role('button', name='העתקה למצב החדש', exact=True)).to_be_enabled()
    expect(baseline.locator('.totals').first).to_contain_text('100.00')
    baseline.get_by_role('button', name='העתקה למצב החדש', exact=True).click()
    expect(proposal.locator('.totals').first).to_contain_text('100.00')
    expect(proposal.get_by_role('button', name='החרגה', exact=True)).to_be_visible()
    assert page.locator('html').get_attribute('dir') == 'rtl'
    page.reload()
    expect(page.locator('.comparison-section')).to_have_count(0)
    assert not errors, errors
    browser.close()
print('Proposal browser check passed')
